# Site settings
title: The Sakurity Blog
email: homakov@gmail.com
description: >
  Boutique infosec consultancy
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://sakurity.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
