# Site settings
title: The Sakurity Blog
email: info@sakurity.com
description: >
  Infosec Playboy.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://sakurity.com" # the base hostname & protocol for your site
twitter_username: sakuritynetwork

# Build settings
markdown: kramdown
